sudo: required
dist: trusty

services:
  - docker

env:
  - DOCKER_COMPOSER_VERSION=1.4.1

matrix:
  fast_finish: true
  include:
    - env: DIR=5.6
    - env: DIR=7.0
    - env: DIR=7.1

before_script:
  - docker build --rm --tag herloct/composer:$TRAVIS_BRANCH-$DIR $DIR
  - docker run --rm herloct/composer:$TRAVIS_BRANCH-$DIR
  - rm -rf tests

script:
  - mkdir tests tests/composer
  - cd tests
  - >
    docker run --rm --user $(id -u):$(id -g)
    --volume $(pwd):/project --volume $(pwd)/composer:/composer/cache
    herloct/composer:$TRAVIS_BRANCH-$DIR require slim/slim --ignore-platform-reqs
  - ls -la .
  - if [[ ! -f "composer.json" ]]; then exit 1; fi
  - if [[ ! -f "composer.lock" ]]; then exit 1; fi
  - ls -la vendor
  - if [[ ! -f "vendor/autoload.php" ]]; then exit 1; fi
  - if [[ ! -d "vendor/slim/slim" ]]; then exit 1; fi
  - ls -la composer
  - if [[ ! -d "composer/files/slim" ]]; then exit 1; fi

after_success:
  - if [ "$TRAVIS_BRANCH" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push herloct/composer:$DOCKER_COMPOSER_VERSION-php$DIR-$TRAVIS_BRANCH;
    fi
  - if [ "$TRAVIS_TAG" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push herloct/composer:$DOCKER_COMPOSER_VERSION-php$DIR;
    fi
