sudo: required
dist: trusty

services:
  - docker

matrix:
  fast_finish: true
  include:
    - env: DIR=5.6
    - env: DIR=7.0
    - env: DIR=7.1

cache:
  directories:
    - composer

before_script:
  - docker build --rm --tag herloct/composer:$TRAVIS_BRANCH-$DIR $DIR
  - docker run --rm herloct/composer:$TRAVIS_BRANCH-$DIR
  - rm -rf tests

script:
  - mkdir tests
  - echo $USER
  - echo $(id -u):$(id -g)
  - docker run --rm --volume tests:/project --volume composer:/composer/cache herloct/composer:$TRAVIS_BRANCH-$DIR require slim/slim --ignore-platform-reqs
  - if [[ ! -f "tests/composer.json" ]]; then exit 1; fi
  - if [[ ! -f "tests/composer.lock" ]]; then exit 1; fi
