sudo: required
dist: trusty

services:
  - docker

language: php

matrix:
  fast_finish: true
  include:
    - php: '5.6'
      env: DIR=5.6
    - php: '7.0'
      env: DIR=7.0
    - php: '7.1'
      env: DIR=7.1

install: true

before_script:
  - docker build --rm --tag herloct/composer:$TRAVIS_BRANCH-$DIR $DIR
  - docker run --rm herloct/composer:$TRAVIS_BRANCH-$DIR
  - rm -rf tests

script:
  - mkdir tests
  - cd tests
  - docker run --rm --volume $(pwd):/project herloct/composer:$TRAVIS_BRANCH-$DIR require slim/slim
  - if [[ ! -f "composer.json" ]]; then exit 1; fi
  - if [[ ! -f "composer.lock" ]]; then exit 1; fi
