sudo: required
dist: trusty

services:
  - docker

matrix:
  fast_finish: true
  include:
    - env:
      - COMPOSER_VERSION=1.4.1
      - PHP_VERSION=5.6
    - env:
      - COMPOSER_VERSION=1.4.1
      - PHP_VERSION=7.0
    - env:
      - COMPOSER_VERSION=1.4.1
      - PHP_VERSION=7.1

before_script:
  - docker build --rm --tag herloct/composer:$COMPOSER_VERSION-php$PHP_VERSION-$TRAVIS_BRANCH $PHP_VERSION
  - docker run --rm herloct/composer:$COMPOSER_VERSION-php$PHP_VERSION-$TRAVIS_BRANCH
  - rm -rf tests

script:
  - mkPHP_VERSION tests tests/composer
  - cd tests
  - >
    docker run --rm --user $(id -u):$(id -g)
    --volume $(pwd):/project --volume $(pwd)/composer:/composer/cache
    herloct/composer:$COMPOSER_VERSION-php$PHP_VERSION-$TRAVIS_BRANCH require slim/slim --ignore-platform-reqs
  - ls -la .
  - if [[ ! -f "composer.json" ]]; then exit 1; fi
  - if [[ ! -f "composer.lock" ]]; then exit 1; fi
  - ls -la vendor
  - if [[ ! -f "vendor/autoload.php" ]]; then exit 1; fi
  - if [[ ! -d "vendor/slim/slim" ]]; then exit 1; fi
  - ls -la composer
  - if [[ ! -d "composer/files/slim" ]]; then exit 1; fi

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push herloct/composer:$COMPOSER_VERSION-php$PHP_VERSION-$TRAVIS_BRANCH
  - if [[ $TRAVIS_TAG ]]; then
    docker tag herloct/composer:$COMPOSER_VERSION-php$PHP_VERSION-$TRAVIS_BRANCH herloct/composer:$COMPOSER_VERSION-php$PHP_VERSION;
    docker push herloct/composer:$COMPOSER_VERSION-php$PHP_VERSION;
    fi
